# Credits @rencprx 
# dont't remove credit
# you noob:v

version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION1: $STRING_SESSION1
      LOG_SESSION: $LOG_SESSION
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      DURATION_LIMIT: $DURATION_LIMIT
      UPSTREAM_REPO: $UPSTREAM_REPO
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH
      ASSISTANT_PREFIX: $ASSISTANT_PREFIX
      SUDO_USERS: $SUDO_USERS
